### PR TITLE
use standard import statements (relative imports)

### PR DESCRIPTION
**Pull request by berleant**
This is necessary for the pyinstaller build of the merge CLI to work. To check that these changes don't break anything, I ran it through all our workflows and tested it through inkscape on my machine. It appears not to break anything. I do wonder if there's a reason to keep the import statements unchanged though. @oskay

### CODE REVIEW

**Comment by oskay** [comment]
I don't see any downsides, but please also give a version bump to 2.1

**Comment by berleant** [comment]
Done, let me know whenever this gets uploaded to pypi!

**Comment by oskay** [comment]
Merged.

**Comment by oskay** [comment]
Updated on pypi! @berleant

**Pull request merged**
